<a href="https://colab.research.google.com/github/yulius37/Data-Mining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('DATAMINING1.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Jarum' 10.0 72000.0]
 ['Super' 80.0 48000.0]
 ['Gudang' 40.0 54000.0]
 ['Jarum' 50.0 61000.0]
 ['Super' 60.0 nan]
 ['Gudang' 30.0 58000.0]
 ['Jarum' 20.0 10000.0]
 ['Super' nan 79000.0]
 ['Gudang' 55.0 83000.0]
 ['Jarum' 90.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Jarum' 10.0 72000.0]
 ['Super' 80.0 48000.0]
 ['Gudang' 40.0 54000.0]
 ['Jarum' 50.0 61000.0]
 ['Super' 60.0 59111.11111111111]
 ['Gudang' 30.0 58000.0]
 ['Jarum' 20.0 10000.0]
 ['Super' 48.333333333333336 79000.0]
 ['Gudang' 55.0 83000.0]
 ['Jarum' 90.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 10.0 72000.0]
 [0.0 0.0 1.0 80.0 48000.0]
 [1.0 0.0 0.0 40.0 54000.0]
 [0.0 1.0 0.0 50.0 61000.0]
 [0.0 0.0 1.0 60.0 59111.11111111111]
 [1.0 0.0 0.0 30.0 58000.0]
 [0.0 1.0 0.0 20.0 10000.0]
 [0.0 0.0 1.0 48.333333333333336 79000.0]
 [1.0 0.0 0.0 55.0 83000.0]
 [0.0 1.0 0.0 90.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 20.0 10000.0]
 [0.0 0.0 1.0 60.0 59111.11111111111]
 [0.0 1.0 0.0 10.0 72000.0]
 [0.0 1.0 0.0 50.0 61000.0]
 [0.0 0.0 1.0 80.0 48000.0]
 [0.0 0.0 1.0 48.333333333333336 79000.0]
 [1.0 0.0 0.0 55.0 83000.0]
 [1.0 0.0 0.0 30.0 58000.0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 40.0 54000.0]
 [0.0 1.0 0.0 90.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -1.1305377045989031 -2.2762378235955425]
 [0.0 0.0 1.0 0.7406971168061781 0.016207902475046432]
 [0.0 1.0 0.0 -1.5983464099501734 0.6178452423487757]
 [0.0 1.0 0.0 0.2728884114549078 0.10437889193929993]
 [0.0 0.0 1.0 1.6763145275087186 -0.5024449767264442]
 [0.0 0.0 1.0 0.19492029389636284 0.9445965562457148]
 [1.0 0.0 0.0 0.506792764130543 1.1313115927582515]
 [1.0 0.0 0.0 -0.6627289992476328 -0.03565738544510256]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 -0.1949202938963625 -0.2223724219576392]
 [0.0 1.0 0.0 2.144123232859989 0.3844514467081049]]
